<?php

/**
 * @file
 * Field Machine Name (PARA: Refer to Paragraph fields. Add all the fields by using paragraph entity type)
 */

// Common Constants.
define('TEMPLATE_ONE', 'template_one');
define('TEMPLATE_TWO', 'template_two');
define('TEMPLATE_THREE', 'template_three');


define('DATA', 'data');

// Template One Constants.


// Template Two Constants.


// Template Three Constants.


// Template Four Constants.


// Template Five Constants.


// Template Six Constants.


// Template Seven Constants.


// Template Eight Constants.


// Template Nine Constants.
